<?
$PERM["/"]["2"]="D";
$PERM["/"]["12"]="R";
$PERM["/"]["13"]="X";
$PERM["/"]["17"]="R";
$PERM["/"]["*"]="D";
$PERM["bitrix"]["12"]="R";
$PERM["bitrix"]["17"]="R";
$PERM["upload"]["*"]="R";
$PERM["upload"]["5"]="T_8";
$PERM["upload"]["17"]="W";
$PERM["about"]["9"]="T_9";
$PERM["company"]["9"]="T_9";
$PERM["apconnect"]["*"]="R";
$PERM["marketplace"]["*"]="R";
$PERM["pub"]["*"]="R";
$PERM["pub"]["5"]="T_8";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
?>